### ISSUE TITLE
NullReferenceException v50

### ISSUE THREAD

**Issue by nephatrine** [nyakowint/EverythingGoBoom-LC#24]
I'm still getting a NullReferenceException in v50 when I enable v1.2.14.

```
[16:03:03.9862254] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EverythingCanDie.Patches.CreateHealthConfigEntry (EnemyType mob) (at <8ed27b5665df42abbdc1b01dec525899>:IL_0001)
EverythingCanDie.Patches.StartOfRoundPatch () (at <8ed27b5665df42abbdc1b01dec525899>:IL_03A7)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::Start>(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?-1998346548(StartOfRound)
LethalLib.Modules.Items.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at <c68aa40cbbae4bd69cd2fcd50c8f1ae1>:IL_0178)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?-501291648(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?402011872(StartOfRound)
LethalLib.Modules.Utilities.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at <c68aa40cbbae4bd69cd2fcd50c8f1ae1>:IL_019C)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?-1255865704(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?-322778422(StartOfRound)
LethalThings.NetworkConfig.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at O:/github/LethalThings/LethalThings/NetworkConfig.cs:272)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?-624879156(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?-616256328(StartOfRound)
LethalThings.Patches.Miscellaneous.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at O:/github/LethalThings/LethalThings/Patches/Miscellaneous.cs:210)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?719058948(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?-1416038298(StartOfRound)
LethalThings.Patches.Debug.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at O:/github/LethalThings/LethalThings/Patches/Debug.cs:109)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?683492832(StartOfRound)

[16:03:03.9862254] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
EverythingCanDie.Patches.CreateHealthConfigEntry (EnemyType mob) (at <8ed27b5665df42abbdc1b01dec525899>:IL_0001)
EverythingCanDie.Patches.StartOfRoundPatch () (at <8ed27b5665df42abbdc1b01dec525899>:IL_03A7)
(wrapper dynamic-method) StartOfRound.DMD<StartOfRound::Start>(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?-1998346548(StartOfRound)
LethalLib.Modules.Items.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at <c68aa40cbbae4bd69cd2fcd50c8f1ae1>:IL_0178)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?-501291648(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?402011872(StartOfRound)
LethalLib.Modules.Utilities.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at <c68aa40cbbae4bd69cd2fcd50c8f1ae1>:IL_019C)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?-1255865704(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?-322778422(StartOfRound)
LethalThings.NetworkConfig.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at O:/github/LethalThings/LethalThings/NetworkConfig.cs:272)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?-624879156(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?-616256328(StartOfRound)
LethalThings.Patches.Miscellaneous.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at O:/github/LethalThings/LethalThings/Patches/Miscellaneous.cs:210)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?719058948(StartOfRound)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<StartOfRound::Start>?-1416038298(StartOfRound)
LethalThings.Patches.Debug.StartOfRound_Start (On.StartOfRound+orig_Start orig, StartOfRound self) (at O:/github/LethalThings/LethalThings/Patches/Debug.cs:109)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Hook<StartOfRound::Start>?683492832(StartOfRound)
```

**Comment by nephatrine** [comment]
I have quite a few mods enabled unfortunately so it's possible it's a conflict with some other mod. I'm working on disabling things and retrying one by one to try to see if that's the case.

**Comment by nephatrine** [comment]
It seems to be LLL that this mod has issues with for me at least. Is there any way to resolve this?

**Comment by Entity378** [comment]
The problem should have been fixed with version 1.2.17 .

**Comment by nephatrine** [comment]
Okay, so I'm still getting the issue. When I disable LLL, it seems to work fine but when I enable it, I get that error still. Under the impression other people weren't having issues though I took a look to see if its actually maybe one of my LLL-dependent mods that is the cause. If I enable LLL, but disable all my LLL mods I don't get the error. Going through them one-by-one it seems like LC_Office is at fault. I guess either the Shrimp or Halt are causing some sort of issue. I'm not sure why I just assumed it was LLL itself.

**Comment by Entity378** [comment]
I'm not sure, but I think the LC Office mobs don't have the enemyHP variable in their code, so when EverythingCanDie tries to read that variable and change it it gives an error

**Comment by Entity378** [comment]
the problem has been solved but I still have to do one more thing for RadMechs so you will have to wait for the new version to be released
